name: Deploy Exercise Manager

on:
  workflow_dispatch:

jobs:
  deploy-all:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
         aws-region: us-east-1


      - name: Build Docker
        run: |
          cd "python - app"
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/exercise-manager:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/exercise-manager:latest

      - name: Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
          terraform_wrapper: false

      - name: Deploy Infrastructure
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
          echo "LB_DNS=$(terraform output -raw load_balancer_dns)" >> $GITHUB_ENV

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          sleep 60

      - name: Deploy App
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          cd ansible
          ansible-playbook -i inventory.ini docker-deploy.yml --private-key ~/.ssh/id_rsa

      - name: Done
        run: |
          echo "âœ… SUCCESS! App at: http://${{ env.LB_DNS }}"